### ISSUE TITLE
Persistence is not working on windows 

### ISSUE THREAD

**Issue by nikirana22** [appsup-dart/firebase_dart#41]
I'm calling _database.setPersistenceEnabled(true)  and also called FirebaseDart.setup(storagePath: 'E:/firebasedart');
but whenever i'm calling ref() but this is not working 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed host lookup: 'firebasestorage.googleapis.com'
#0      IOClient.send (package:http/src/io_client.dart:88:7)
<asynchronous suspension>
#1      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:871:15)
<asynchronous suspension>
#2      HttpClient.send (package:firebase_dart/src/storage/impl/http_client.dart:34:9)
<asynchronous suspension>
#3      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#4      ResourceClient.multipartUpload (package:firebase_dart/src/storage/impl/resource_client.dart:127:20)
<asynchronous suspension>
#5      UploadTaskImpl._oneShotUpload (package:firebase_dart/src/storage/impl/task.dart:334:23)
<asynchronous suspension>
#6      UploadTaskImpl._start.<anonymous closure> (package:firebase_dart/src/storage/impl/task.dart:146:9)
<asynchronous suspension>
#7      objectSynchronized.<anonymous closure> (package:synchronized/src/extension_impl.dart:37:18)
<asynchronous suspension>
#8      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#9      objectSynchronized (package:synchronized/src/extension_impl.dart:34:12)
<asynchronous suspension>

please correct me if I'm doing something wrong

**Comment by rbellens** [comment]
this stack trace has to do with firebase storage, not the database. It seems you are getting this error when uploading a file to storage. So, I don't see how this can be related to setting persistence.
