### ISSUE TITLE
signInWithCustomToken throws HandshakeException

### ISSUE THREAD

**Issue by eximius313** [appsup-dart/firebase_dart#43]
When I try to authenticate using custom token, this line:
```dart
auth.signInWithCustomToken(customAuthToken)
```

throws:
```
HandshakeException: Handshake error in client (OS Error:
I/flutter (15029): 	CERTIFICATE_VERIFY_FAILED: certificate is not yet valid(handshake.cc:393))
I/flutter (15029): 	#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
I/flutter (15029): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
I/flutter (15029): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:915:54)
I/flutter (15029): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1044:19)
```

could you please fix that?

**Comment by eximius313** [comment]
It seems to be related with [this bug](https://github.com/dart-lang/http/issues/627), but I'm testing it on Emulator with Android 12 and I doubt that Google is using Let's Encrypt [here](https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit)

**Comment by eximius313** [comment]
It was probably the [date&time issue](https://stackoverflow.com/a/68604631)
